### ISSUE TITLE
Mixed winding order confuses MapNik renderer

### ISSUE THREAD

**Issue by pramsey** [CartoDB/mapnik#11]
The complex polygon in [this KML file](https://github.com/CartoDB/mapnik/files/81236/foo.kml.zip) has a mixture of winding orders, which cause MapNik to render the holes as filled (one hole is probably reversed relative to the others).

![screenshot_09](https://cloud.githubusercontent.com/assets/113883/12172906/9a63333e-b508-11e5-8d99-a85075bd18c8.png)

When the polygon is "fixed" by using `ST_ForceRHR` on it, it renders correctly (as seen above).

**Comment by pramsey** [comment]
Open question is whether it's worth fixing. The workaround is clear, and not too expensive in cases where this manifests, just wrap the geometry in `ST_ForceRHR`. Checking for this in every render would add overhead that would only yield an improvement in extremely rare cases (though I suppose the since the check would only be required in cases where # holes > 1 the check itself would only get run infrequently). However, orientation checking is not cheap (basically you calculate area and see if it's positive or negative).

**Comment by pramsey** [comment]
As a proof of the point, I was able to generate the same effect by creating a polygon with two holes, one clock-wise and the other anti-clock-wise.

![screenshot_10](https://cloud.githubusercontent.com/assets/113883/12173472/d42068c8-b50b-11e5-82d0-b91dcb9ec6d2.png)

**Comment by pramsey** [comment]
Actually, the problem seems to be having the exterior and interior rings with the same order. These rings all go anti-clockwise. So MapNik expects holes to always run counter to hulls? That seems like a big assumption, in a world of ugly data.

![screenshot_11](https://cloud.githubusercontent.com/assets/113883/12173611/a9c4b286-b50c-11e5-9dcf-4eb33b62aea8.png)

**Comment by pramsey** [comment]
This was canvassed in mapnik community https://github.com/mapbox/tilemill/issues/2110#issuecomment-75897323 and a fix applied https://github.com/mapnik/mapnik/issues/2371#issuecomment-52992474
 (maybe to the 3.x branch)

**Comment by pramsey** [comment]
For @rochoa to review. It's tiny, but it's really deep in the stack, could have some unexpected effects in unexpected places.

**Comment by rochoa** [comment]
_Unexpected effects in unexpected places_ sounds like a doble negation, so ... what could go wrong?
