### ISSUE TITLE
[Raster] Check impact of requesting DISTINCT geometries

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/mapnik#20]
Current query example:
```sql
SELECT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)) AS geom FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857)
```

Proposed:
```sql
SELECT DISTINCT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)) AS geom FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857)
```

Reasoning: For big datasets (or tiles with a lot of geometries) it takes way longer for rendering than extracting the information from the database, e.g (from previous query):
```
X-Tiler-Profiler:{"authorizedByAPIKey":1,"res":17283,"getTileOrGrid":17283,"getRenderer":286,"render-png":16997,"Mapnik":{"Time (us)":16986123,"Calls":1,"Setup":{"Time (us)":683344,"Calls":1,"Datasource: Get Features":{"Time (us)":683314,"Calls":1}},"Render":{"Time (us)":16301163,"Calls":1,"Style":{"Time (us)":16301157,"Calls":1,"features":985785}}},"tiles in metatile":1,"total":17284}
```
~1M features returned from Postgresql query: Database time: 0.683sec, Rendering time: 16.3 sec

Impact should be checked in tiles with low and high number of geometries and using both points and polygons.

**Comment by Algunenano** [comment]
It has come to my attention that this would have impact in the renderer. Maybe using GROUP BY to return geometry, count(geometry) would be useful to reduce calculations

**Comment by jgoizueta** [comment]
It would be nice to be able to have control  over the wrapping that Mapnik postgis datasource applies to the queries. Or at least have it specialised per geometry type. I took a brief look at that [during 1000x](https://github.com/CartoDB/1000x/issues/5). But it seems that for it to be efficient (avoid sompling geometries) we should have specific geometry types in `the_geometry_webmercator` (e.g. `Geometry(POINT,3857)` instead of `Geometry(GEOMETRY,3857)`)

I think we could start by having specialised per-type queries in the ST_AsMVT workflow first some we can experiment more easily.

**Comment by Algunenano** [comment]
Some test with different queries:

* **CURRENT**:

```sql
SELECT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)) AS geom FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857);
```

 Seq Scan on yellow_1m  (cost=0.00..70801.96 rows=999999 width=32) (actual time=0.024..564.225 rows=**985785** loops=1)
   Filter: (the_geom_webmercator && '01030000A0110F00000100000005000000CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000CDCCCC44F81B73C1CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73C10000000000000000CDCCCC44F81B73C1CDC
CCC44F81B73C10000000000000000'::geometry)
   Rows Removed by Filter: 14214
 Planning time: 0.366 ms
 Execution time: **588.696** ms
 

```                     geom                     
----------------------------------------------
 \x010100000048e17a142f695fc10ad7a37066fd5241
 \x010100000048e17a142f695fc10ad7a37066fd5241
 \x010100000048e17a142f695fc10ad7a37066fd5241
 \x010100000099999979016d5fc1b81e850b94f95241
 \x010100000099999979016d5fc1666666a6c1f55241
 \x010100000048e17a142f695fc10ad7a37066fd5241
 \x010100000048e17a142f695fc10ad7a37066fd5241
 ...
```



* **DISTINCT**:
This has issues in rendering (information lost):

```sql
SELECT DISTINCT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)) AS geom FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857);
```
 HashAggregate  (cost=73301.96..113301.92 rows=999999 width=32) (actual time=695.015..698.719 rows=**271** loops=1)
   Group Key: st_asbinary(st_simplify(st_snaptogrid(yellow_1m.the_geom_webmercator, '0'::double precision, '0'::double precision, '3913.58'::double precision, '3913.58'::double precision), '7827.15'::double precision))
   ->  Seq Scan on yellow_1m  (cost=0.00..70801.96 rows=999999 width=32) (actual time=0.048..557.268 rows=985785 loops=1)
         Filter: (the_geom_webmercator && '01030000A0110F00000100000005000000CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000CDCCCC44F81B73C1CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73C10000000000000000CDCCCC44F81B7
3C1CDCCCC44F81B73C10000000000000000'::geometry)
         Rows Removed by Filter: 14214
 Planning time: 0.385 ms
 Execution time: **713.850** ms

 * Output sample:

```                     geom                     
----------------------------------------------
 \x01010000000000006071b95fc114ae47e133145141
 \x010100000000000080e5595fc1000000a0dd085341
 \x010100000000000080e5595fc10ad7a37066fd5241
 \x010100000000000080e5595fc114ae4741eff15241
 \x010100000000000080e5595fc148e17a3427185341
 \x010100000000000080e5595fc152b81e05b00c5341
 \x010100000000000080e5595fc15c8fc2d538015341
 ...
```


* **Using COUNT**:

This requires adapting Mapnik's renderer:
```sql
SELECT ST_AsBinary(ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)) AS geom, count(1) FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857)
GROUP BY geom;
```

 HashAggregate  (cost=75801.95..115801.91 rows=999999 width=40) (actual time=727.753..731.571 rows=**271** loops=1)
   Group Key: st_asbinary(st_simplify(st_snaptogrid(yellow_1m.the_geom_webmercator, '0'::double precision, '0'::double precision, '3913.58'::double precision, '3913.58'::double precision), '7827.15'::double precision))
   ->  Seq Scan on yellow_1m  (cost=0.00..70801.96 rows=999999 width=32) (actual time=0.027..568.341 rows=985785 loops=1)
         Filter: (the_geom_webmercator && '01030000A0110F00000100000005000000CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000CDCCCC44F81B73C1CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73C10000000000000000CDCCCC44F81B7
3C1CDCCCC44F81B73C10000000000000000'::geometry)
         Rows Removed by Filter: 14214
 Planning time: 0.411 ms
 Execution time: **746.047** ms
(7 rows)

  * Output sample:

```                     geom                     | count  
----------------------------------------------+--------
 \x01010000000000006071b95fc114ae47e133145141 |      1
 \x010100000000000080e5595fc1000000a0dd085341 |      5
 \x010100000000000080e5595fc10ad7a37066fd5241 |     48
 \x010100000000000080e5595fc114ae4741eff15241 |     78
 \x010100000000000080e5595fc148e17a3427185341 |      1
 \x010100000000000080e5595fc152b81e05b00c5341 |      3
 \x010100000000000080e5595fc15c8fc2d538015341 |      6
 \x010100000000000080e5595fc1666666a6c1f55241 |    235
 ...
 ```
 

 
 * **COUNT and BINARY AFTER GROUP**:
 
 ```sql
WITH geometries AS
(
SELECT ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15) AS geom_c, count(1) as count FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857)
GROUP BY geom_c
)
SELECT ST_AsBinary(geom_c) as geom, count FROM geometries;
```

 CTE Scan on geometries  (cost=167959.70..212959.65 rows=999999 width=40) (actual time=835.849..1145.783 rows=**271** loops=1)
   CTE geometries
     ->  GroupAggregate  (cost=145459.72..167959.70 rows=999999 width=40) (actual time=835.842..1145.646 rows=271 loops=1)
           Group Key: (st_simplify(st_snaptogrid(yellow_1m.the_geom_webmercator, '0'::double precision, '0'::double precision, '3913.58'::double precision, '3913.58'::double precision), '7827.15'::double precision))
           ->  Sort  (cost=145459.72..147959.72 rows=999999 width=32) (actual time=835.834..911.901 rows=985785 loops=1)
                 Sort Key: (st_simplify(st_snaptogrid(yellow_1m.the_geom_webmercator, '0'::double precision, '0'::double precision, '3913.58'::double precision, '3913.58'::double precision), '7827.15'::double precision))
                 Sort Method: quicksort  Memory: 101591kB
                 ->  Seq Scan on yellow_1m  (cost=0.00..45801.98 rows=999999 width=32) (actual time=0.022..458.634 rows=985785 loops=1)
                       Filter: (the_geom_webmercator && '01030000A0110F00000100000005000000CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000CDCCCC44F81B73C1CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73C1000000000000000
0CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000'::geometry)
                       Rows Removed by Filter: 14214
 Planning time: 0.453 ms
 Execution time: **1147.329** ms
(12 rows)


  * Output sample:
```
                     geom                     | count  
----------------------------------------------+--------
 \x0101000000ae47e15a9c9a5bc1c2f5289c34ad4341 |      1
 \x01010000003333339391205fc15c8fc2f528934e41 |      1
 \x0101000000a4703deace835dc10ad7a3f0367f5141 |      1
 \x01010000003333339391205fc18fc2f568b5495141 |      1
 \x01010000000000006071b95fc114ae47e133145141 |      1
 \x010100000048e17a142f695fc19a9999b96dbc5241 |     10
```


Seems that this is slower due to the calls to lwgeom_eq to compare geometries (which aparently it's really slow):



 * **COUNT and BINARY AFTER GROUP (Comparing as text)**:
```sql
WITH geometries AS
(
SELECT ST_Simplify(ST_SnapToGrid("the_geom_webmercator",3913.58), 7827.15)::text AS geom_c, count(1) as count FROM 
    (SELECT * FROM yellow_1m) as cdbq
WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 -20037508.3,20037508.3 20037508.3)'::box3d, 3857)
GROUP BY geom_c
)
SELECT ST_AsBinary(geom_c::geometry) as geom, count FROM geometries;
```

 CTE Scan on geometries  (cost=190801.84..238301.79 rows=999999 width=40) (actual time=756.536..760.611 rows=**271** loops=1)
   CTE geometries
     ->  HashAggregate  (cost=113301.92..190801.84 rows=999999 width=40) (actual time=756.529..760.419 rows=271 loops=1)
           Group Key: (st_simplify(st_snaptogrid(yellow_1m.the_geom_webmercator, '0'::double precision, '0'::double precision, '3913.58'::d
ouble precision, '3913.58'::double precision), '7827.15'::double precision))::text
           ->  Seq Scan on yellow_1m  (cost=0.00..108301.92 rows=999999 width=32) (actual time=0.026..592.595 rows=985785 loops=1)
                 Filter: (the_geom_webmercator && '01030000A0110F00000100000005000000CDCCCC44F81B73C1CDCCCC44F81B73C10000000000000000CDCCCC
44F81B73C1CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73410000000000000000CDCCCC44F81B7341CDCCCC44F81B73C10000000000000000C
DCCCC44F81B73C1CDCCCC44F81B73C10000000000000000'::geometry)
                 Rows Removed by Filter: 14214
 Planning time: 0.459 ms
 Execution time: **775.974** ms
(9 rows)

* Output sample:
```                     geom                     | count  
----------------------------------------------+--------
 \x0101000000a4703d4a8a615fc15c8fc2d538015341 |     11
 \x0101000000d7a3703dc2875fc1ae47e13a0b055341 |      1
 \x0101000000b81e85eb9b4a5fc19a999999f91b5341 |      1
 \x010100000048e17a142f695fc15c8fc2d538015341 |  72766
 \x0101000000a4703d4a8a615fc1666666a6c1f55241 |     53
 \x0101000000295c8fa2948b5fc1ae47e13a0b055341 |      1
 \x010100000052b81ee5b75d5fc1f6285ccf54145341 |      3
 \x0101000000ae47e11a13565fc114ae4741eff15241 |    148
 \x010100000099999979016d5fc1b81e850b94f95241 | 204628
 ```

**Comment by rafatower** [comment]
For rasters in production we're doing something like `SELECT ST_AsTWKB(ST_Simplify(ST_RemoveRepeatedPoints()))` (note the TWKB, tiny well-known-binary). I don't know about the actual implementation details of `ST_RemoveRepeatedPoints` and how it compares to `DISTINCT`. See the [postgis input plugin](https://github.com/mapnik/mapnik/blob/f02a259011ec397f8152b0ad9b353483e80d5f96/plugins/input/postgis/postgis_datasource.cpp#L777-L791) in mapnik. HTH

**Comment by Algunenano** [comment]
ST_RemoveRepeatedPoints removes duplicated points inside a geometry. What I'm trying to achieve is to not return duplicated geometries; in fact, as that apparently has some issues in rendering, I'm planning to return unique geometries + count to see if there is an improvement in the render side.

**Comment by Algunenano** [comment]
After some testing I've seen several important things
* Using DISTINCT when rendering tiles in Mapnik with a lot of geometries (100k+) reduces the rendering time in ~95% and, as rendering takes most of the time in this cases (90%) it has a big impact.
* Mapnik map config xml supports GROUP BY, so a similar approach could be implemented directly from Builder (group by the_geom_webmercator and any other column needed).

As previously mentioned this approach only has impact in tiles with a lot of geometries, but it isn't that important for smaller datasets/less geometries per tile. I see a way simpler solution: big datasets (let's say > 500k) should not be using "None" aggregation by default. Aggregations already group rows depending on what it needs it, so instead of trying to group geometries under the hood in the "No aggregation mode" we should be moving maps like this into using aggregations .

**Comment by Algunenano** [comment]
Pending having more knowledge about what the end use would be, I'm thinking about 2 complementary solutions to the real issue which is performance issues when rendering big datasets:
* Add a visual alert when you are using "NONE" Aggregation with datasets bigger than a certain limit (let's say 100k) to notify the user that he should probably be using some other method to visualize the data. It's my understanding that this can and should be done at UI level (so Builder).
* Speed up our aggregations, which means improving the base system (Posgresql + PostGIS) and our aggregation functions (https://github.com/CartoDB/cartodb-postgresql).

This is obviously also complementary to, if needed, adding new aggregation / analysis tools more suitable for data of this size.

**Comment by Algunenano** [comment]
Closing for now
