### ISSUE TITLE
Apply patch to enable the use of the @ character in SQL queries

### ISSUE THREAD

**Issue by enekid** [CartoDB/mapnik#29]
This issue documents a [bug](https://github.com/CartoDB/support/issues/1136) related to the use of the `@` character in the SQL queries sent to mapnik. It has being [patched](https://github.com/mapnik/mapnik/pull/3618) in the future [3.1 mapnik release](https://github.com/mapnik/mapnik/wiki/API-changes-between-v3.0-and-v3.1), but not in v3.0.15 (the version used currently in this fork), because it has breaking changes. 

Mapnik 3.0.X has a bug with the `@` character in the SQL queries. Whenever it finds a `@` it treats it as a [render-time variable](https://github.com/mapnik/mapnik/issues/2553). Therefore the use of the `@` character corrupts the SQL query (eg. email addresses: tesla@baddogs.com).

[#1136](https://github.com/CartoDB/support/issues/1136) could be fixed applying the patch, **but** at the same time, all uses of `render-time variables` in [windshaft](https://github.com/CartoDB/Windshaft-cartodb) should be surrounded by `!` characters.

**Comment by Algunenano** [comment]
Initial branch with the commits modified to be compatible with our 3.0.15 build in https://github.com/Algunenano/mapnik/tree/v3.0.15-carto_postgis_quoting

Pending reviewing Windshaft/Windshaft-cartodb for render-time-variables usages in queries.

**Comment by Algunenano** [comment]
I have it working locally with the branch above:
![image](https://user-images.githubusercontent.com/664253/35520091-5013c5f4-0516-11e8-8c43-1255e5268712.png)

I haven't seen any usage of render-time variables but I have to do a deeper search.

**Comment by Algunenano** [comment]
I haven't found any usage of this kind of variables in Windshaft. @enekid did you see anything while you were investigating the issue?

**Comment by enekid** [comment]
Nothing. I was warned by @rafatower about this. Maybe he can guide us.

**Comment by Algunenano** [comment]
I've only seen it used in the 1000x branch (https://github.com/CartoDB/Windshaft-cartodb/blob/1000x-tt/lib/cartodb/utils/substitution-tokens.js) so I'm guessing we should be ok.

**Comment by Algunenano** [comment]
Merging. To be tested in next Mapnik release.
