### ISSUE TITLE
Metrics: Add cache hits / missed

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/mapnik#39]
With the introduction of the marker cache we should measure how many hits / misses we have.

**Comment by rafatower** [comment]
Done in a bunch of PR's:
- https://github.com/CartoDB/mapnik/pull/45
- https://github.com/CartoDB/mapnik/pull/46
- https://github.com/CartoDB/mapnik/pull/47
- https://github.com/CartoDB/mapnik/pull/48
- https://github.com/CartoDB/mapnik/pull/49
- https://github.com/CartoDB/mapnik/pull/50
- https://github.com/CartoDB/mapnik/pull/51
