### ISSUE TITLE
Cache: Study the possibility of setting it as an option

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/mapnik#40]
Right now we have them on as default so benchmarking or checking the difference between using the marker cache or not means switching the whole Mapnik stack completely.

**Comment by Algunenano** [comment]
Also it'd be interesting to be able to control the sub-sampling used or even the cache policy if several are implemented.

**Comment by rafatower** [comment]
Addressed in https://github.com/CartoDB/mapnik/pull/43
