### ISSUE TITLE
TWKB does not paint geometries in high zoom levels

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/mapnik#9]
steps to reproduce:
- use postgis datasource, twkb_encoding: true
- have a point at some high coordinates away from 0, 0 (for example, coast of California, north pole)
- try to render it at high zoom levels (reproduced with zoom >=19)

It seems changing the value of `twkb_rounding_adjustment` to a high level changes the zoom level the point is visible on, so it seems like it is related.

See #3, #5 to find where TWKB is implemented.

cc @rochoa @javisantana @pramsey

**Comment by iriberri** [comment]
SB/7174891 cc @ernesmb

**Comment by zenitraM** [comment]
We've now disabled TWKB in prod for the time being
